repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Use the latest version
    hooks:
      - id: trailing-whitespace
        exclude: ^docs/
      - id: end-of-file-fixer
        exclude: ^docs/
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [--fix]
        files: ^aixplain/v2/
      - id: ruff-format
        files: ^aixplain/v2/

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: coverage run --source=. -m pytest tests/unit
        language: python
        pass_filenames: false
        types: [python]
        always_run: true
        additional_dependencies:
          - coverage
          - pytest
          - pytest-mock
          - pytest-rerunfailures
          - pytest-xdist
          - requests-mock
          - Babel>=2.12.0
          - requests>=2.1.0
          - tqdm>=4.1.0
          - pandas>=2.0.0
          - python-dotenv>=1.0.0
          - validators>=0.20.0
          - filetype>=1.2.0
          - click>=7.1.2
          - PyYAML>=6.0.1
          - dataclasses-json>=0.5.2
          - Jinja2==3.1.6
          - sentry-sdk>=1.0.0
          - pydantic>=2.10.6
          - filelock>=3.0.0
