# This file has been replaced with static enums generated by generate.py
# Please use the static enums from generated_enums.py instead

from .generated_enums import Function, FunctionInputOutput, FunctionParameters

__all__ = ["Function", "FunctionInputOutput", "FunctionParameters"] 
