"""Drift guard for the run-metadata disclosure (BUG-1096).

Agent run payloads carry a ``metaData`` object built by
:func:`aixplain.utils.user_info_utils.build_run_metadata`, populated from a
``https://ipinfo.io/json`` lookup. That collection went undocumented long enough for a
security audit to file it as a defect; the fix was documentation, and documentation
written by hand rots. These tests fail the build when the shipped disclosure stops
matching the code — when a ``metaData`` key is added, renamed or dropped without the
docs following, when a doc loses the disclosure, or when a new module starts sending
``metaData`` without appearing in the call-site tables.

They also pin the two wiring claims the disclosure makes about v2: a direct
``Agent.build_run_payload`` carries ``metaData``, and a session-routed run does not.

Network-free by construction: ``_fetch_ipinfo`` is patched out and the client is a
mock, so no request ever leaves the process.
"""

import pathlib
from unittest import mock

import pytest

from aixplain.utils import user_info_utils

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]

#: Every key ``build_run_metadata()`` returns. The canonical disclosure in
#: ``docs/run-metadata.md`` documents exactly these, field by field.
DOCUMENTED_FIELDS = {
    "userAgent",
    "region",
    "language",
    "ipAddress",
    "latitude",
    "longitude",
    "timezone",
}

#: Hand-written docs that must carry the disclosure. ``docs/api-reference/`` is
#: generated by .github/workflows/docs.yaml and deliberately excluded.
DOCS_WITH_DISCLOSURE = [
    "README.md",
    "README.ar.md",
    "docs/README.md",
    "docs/README.ar.md",
    "docs/run-metadata.md",
    "docs/run-metadata.ar.md",
]

#: The canonical pages, English and Arabic, that carry the full field table.
CANONICAL_PAGES = ["docs/run-metadata.md", "docs/run-metadata.ar.md"]

#: Modules that call ``build_run_metadata()``. Every one of these is listed in the
#: call-site table of both canonical pages.
KNOWN_CALL_SITES = {
    "aixplain/v1/modules/agent/__init__.py",
    "aixplain/v1/modules/team_agent/__init__.py",
    "aixplain/v2/agent.py",
}


def read(relative_path):
    """Return the text of a repo-relative doc, failing loudly if it is missing."""
    path = REPO_ROOT / relative_path
    assert path.is_file(), f"expected doc {relative_path} to exist at {path}"
    return path.read_text(encoding="utf-8")


def test_documented_fields_match_the_payload():
    """A ``metaData`` key the docs do not list is an undisclosed field — the BUG-1096 defect."""
    with mock.patch.object(user_info_utils, "_fetch_ipinfo", return_value={}):
        actual = set(user_info_utils.build_run_metadata())
    assert actual == DOCUMENTED_FIELDS, (
        "build_run_metadata() no longer returns the documented field set. Update "
        "docs/run-metadata.md, docs/run-metadata.ar.md, both READMEs and DOCUMENTED_FIELDS "
        f"together. Undocumented: {sorted(actual - DOCUMENTED_FIELDS)}; "
        f"documented but absent: {sorted(DOCUMENTED_FIELDS - actual)}."
    )


@pytest.mark.parametrize("doc", CANONICAL_PAGES)
@pytest.mark.parametrize("field", sorted(DOCUMENTED_FIELDS))
def test_every_field_is_named_in_the_canonical_page(doc, field):
    """The disclosure names each field explicitly, not as a vague summary."""
    assert field in read(doc), f"{doc} does not name the metaData field {field!r}"


@pytest.mark.parametrize("doc", DOCS_WITH_DISCLOSURE)
def test_disclosure_survives(doc):
    """Every doc that carries the notice must keep naming the payload and the third party."""
    text = read(doc)
    assert "metaData" in text, f"{doc} no longer mentions the metaData payload field"
    assert "ipinfo.io" in text, f"{doc} no longer names ipinfo.io as the lookup service"


@pytest.mark.parametrize("doc", ["README.md", "docs/README.md"])
def test_english_readme_links_the_canonical_page(doc):
    """A disclosure nobody can reach from the README is not a disclosure."""
    assert "run-metadata.md" in read(doc), f"{doc} does not link the run-metadata page"


@pytest.mark.parametrize("doc", ["README.ar.md", "docs/README.ar.md"])
def test_arabic_readme_links_the_canonical_page(doc):
    """Arabic-reading users get the same notice and the same link — English-only is the bug."""
    assert "run-metadata.ar.md" in read(doc), f"{doc} does not link the Arabic run-metadata page"


def modules_calling_build_run_metadata():
    """Return repo-relative paths of ``aixplain`` modules that call ``build_run_metadata()``."""
    return {
        str(path.relative_to(REPO_ROOT))
        for path in (REPO_ROOT / "aixplain").rglob("*.py")
        if path.name != "user_info_utils.py" and "build_run_metadata(" in path.read_text(encoding="utf-8")
    }


def test_call_sites_still_match_the_docs():
    """If a new module starts sending metaData, the call-site tables must be updated."""
    assert modules_calling_build_run_metadata() == KNOWN_CALL_SITES, (
        "The set of modules sending metaData changed. Update the call-site tables in "
        "docs/run-metadata.md and docs/run-metadata.ar.md, then update KNOWN_CALL_SITES."
    )


@pytest.mark.parametrize("doc", CANONICAL_PAGES)
def test_canonical_page_lists_every_call_site(doc):
    """Each sending module is named in the page's call-site table."""
    text = read(doc)
    for module in sorted(KNOWN_CALL_SITES):
        assert module in text, f"{doc} does not list the call site {module}"


@pytest.mark.parametrize("doc", CANONICAL_PAGES)
def test_canonical_page_documents_the_failure_and_caching_behaviour(doc):
    """The two facts users actually hit: one lookup per process, and silent failure."""
    text = read(doc)
    assert "lru_cache" in text, f"{doc} does not explain that the lookup is cached per process"
    assert "null" in text, f"{doc} does not explain that fields arrive null when the lookup fails"


def test_build_run_metadata_docstring_points_at_the_disclosure():
    """The generated API reference must lead readers to the full disclosure."""
    docstring = user_info_utils.build_run_metadata.__doc__ or ""
    assert "docs/run-metadata.md" in docstring
    for field in DOCUMENTED_FIELDS:
        assert field in docstring, f"build_run_metadata docstring does not mention {field!r}"


def test_module_docstring_names_the_lookup_service():
    """An auditor reading the module should not have to infer the third-party call."""
    assert "ipinfo.io" in (user_info_utils.__doc__ or "")


def test_metadata_degrades_to_nulls_without_a_lookup():
    """The documented failure mode: userAgent survives, everything else is None."""
    with mock.patch.object(user_info_utils, "_fetch_ipinfo", return_value={}):
        meta = user_info_utils.build_run_metadata()
    assert meta["userAgent"] == "sdk"
    assert all(value is None for key, value in meta.items() if key != "userAgent"), meta


def test_v2_run_payload_carries_the_documented_metadata():
    """The v2 claim in the disclosure: a direct v2 agent run really does send ``metaData``.

    v1 coverage lives in ``tests/unit/agent/agent_test.py``
    (``test_run_async_includes_run_metadata``); this is the v2 half, and the reason
    the call-site table lists ``aixplain/v2/agent.py``.
    """
    from unittest.mock import MagicMock

    from aixplain.v2.agent import Agent

    agent = Agent.from_dict({"id": "agent-123", "name": "test-agent"})
    agent.context = MagicMock()

    ipinfo = {
        "ip": "192.0.2.10",
        "country": "US",
        "loc": "37.7749,-122.4194",
        "timezone": "America/Los_Angeles",
    }
    with mock.patch.object(user_info_utils, "_fetch_ipinfo", return_value=ipinfo):
        payload = agent.build_run_payload(query="q")

    assert set(payload["metaData"]) == DOCUMENTED_FIELDS
    assert payload["metaData"] == {
        "userAgent": "sdk",
        "region": "en-US",
        "language": "en",
        "ipAddress": "192.0.2.10",
        "latitude": pytest.approx(37.7749),
        "longitude": pytest.approx(-122.4194),
        "timezone": "America/Los_Angeles",
    }


def test_v2_session_messages_carry_no_metadata():
    """The documented exception: session-routed v2 runs post a message, not a run payload.

    The disclosure says so explicitly; if the session path ever starts attaching
    ``metaData``, the docs become wrong in the direction that matters.
    """
    from unittest.mock import MagicMock

    from aixplain.v2.session import Session

    session = Session.from_dict({"id": "session-123"})
    session.context = MagicMock()
    session.context.client.request.return_value = {"id": "msg-1", "role": "user", "content": "q"}
    session.status = "active"

    session.add_message(role="user", content="q")

    _, kwargs = session.context.client.request.call_args
    payload = kwargs["json"]
    # Guard against a vacuous pass: we must be looking at the real message body.
    assert payload["role"] == "user"
    assert "metaData" not in payload, payload
