"""Guard: no plaintext credentials in the tree, and the scanner stays wired up (ENG-3686).

Two live credentials sat in tracked files for months. ``test_agent_eval.py`` at
the repository root passed a 64-hex platform key as a literal ``api_key=``
argument pointed at ``dev-platform-api``, and ``pipeline_test2.ipynb`` -- a
scratch notebook, also at the root -- set ``TEAM_API_KEY`` to another 64-hex key
and then committed the execution output, which echoed that key back inside
request logs, webhook JWTs and pipeline payloads. Neither file ran under pytest:
both are outside ``testpaths``, so no suite ever looked at them.

Gitleaks now runs on the staged diff via .pre-commit-config.yaml and over the
whole tree in .github/workflows/pre-commit.yaml. That is the real scanner; this
module is the part of it that survives having no network and no Go toolchain,
and it fails in the credential-free ``unit-coverage`` job:

* :func:`test_no_plaintext_key_literals` re-states the specific defect, so a key
  pasted into a file nobody runs is caught by the ordinary unit suite.
* The wiring tests fail if someone drops the hook, the CI step or the config --
  a scanner that has been quietly unhooked reports the same "no leaks found" as
  a clean tree.

The detectors take their root as a parameter so they can be pointed at a
synthetic tree and tested, following ``_blanket_skip_offenders`` in
tests/unit/test_ci_matrix_coverage.py. A guard nobody tested is decorative.
"""

import re
import subprocess
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
PRE_COMMIT_CONFIG = REPO_ROOT / ".pre-commit-config.yaml"
PRE_COMMIT_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "pre-commit.yaml"
GITLEAKS_CONFIG = REPO_ROOT / ".gitleaks.toml"

GITLEAKS_REPO = "https://github.com/gitleaks/gitleaks"

#: A 64-hex platform API key, as a standalone token. Both leaked keys had this
#: shape, and so does every key the platform issues.
_KEY_LITERAL = re.compile(r"(?<![0-9a-fA-F])[0-9a-fA-F]{64}(?![0-9a-fA-F])")

#: A 64-hex string is only a finding when something on the line says it is a
#: credential. Unqualified 64-hex strings are overwhelmingly sha256 digests --
#: lockfile hashes, the artifact checksums in tests/unit/v2/test_agent_artifacts.py,
#: the generator fixtures in tools/generator/fixtures/provenance.json -- and
#: banning those outright would make this guard unrunnable rather than strict.
_CREDENTIAL_CONTEXT = re.compile(r"api[_-]?key|team[_-]?key|access[_-]?key|token|secret|password", re.IGNORECASE)

#: Directories with no hand-written source to protect. ``docs/`` is generated by
#: generate.py and ``uv.lock`` is thousands of sha256 digests; scanning either
#: costs seconds and can only produce noise. The build and cache directories
#: matter only on the synthetic-tree path below, since git tracks none of them.
_SKIP_DIRS = frozenset({".git", ".venv", "venv", "node_modules", "__pycache__", ".pytest_cache", "docs", "build", "dist"})
_SKIP_FILES = frozenset({"uv.lock", "test_secret_scanning.py"})

#: Extensions worth reading. Binary assets cannot carry a reviewable literal.
_TEXT_SUFFIXES = frozenset({".py", ".ipynb", ".json", ".yaml", ".yml", ".toml", ".cfg", ".ini", ".md", ".txt", ".sh", ".env", ".example"})


def _tracked_files(root: Path):
    """Return ``root``'s git-tracked files, or ``None`` when ``root`` is not a checkout.

    Scope is deliberately what git tracks. This guard is about a credential
    reaching history, and the working tree is full of ignored files that hold
    real keys by design: ``.cache/model.json``, which the SDK writes an
    ``api_key`` into on every run, and the ``.env`` that tests/conftest.py loads
    via ``load_dotenv``. Walking those fails the unit suite on any developer
    machine that has ever run the SDK, over files git will never accept.

    ``None`` keeps the synthetic ``tmp_path`` trees below on a plain filesystem
    walk; the check is on ``root`` itself so a temporary directory can never
    inherit an enclosing repository's index.
    """
    if not (root / ".git").exists():
        return None
    try:
        listing = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-z"],
            capture_output=True,
            check=True,
            text=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError) as exc:  # pragma: no cover - needs a broken checkout
        pytest.fail(f"cannot list tracked files under {root}: {exc}")
    return [root / name for name in listing.split("\0") if name]


def _key_literal_offenders(root: Path):
    """Return ``(relative path, line number)`` for each credential-shaped literal under ``root``."""
    tracked = _tracked_files(root)
    candidates = root.rglob("*") if tracked is None else tracked
    offenders = []
    for path in sorted(candidates):
        if not path.is_file():
            continue
        if any(part in _SKIP_DIRS for part in path.parts):
            continue
        if path.name in _SKIP_FILES:
            continue
        if path.suffix not in _TEXT_SUFFIXES:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for lineno, line in enumerate(text.splitlines(), start=1):
            if _KEY_LITERAL.search(line) and _CREDENTIAL_CONTEXT.search(line):
                offenders.append((path.relative_to(root).as_posix(), lineno))
    return offenders


def test_no_plaintext_key_literals():
    """No tracked file pairs a 64-hex literal with a credential-ish name."""
    offenders = _key_literal_offenders(REPO_ROOT)
    assert offenders == [], (
        "64-hex literal on a line naming a credential:\n"
        + "\n".join(f"  {path}:{lineno}" for path, lineno in offenders)
        + "\nIf this is a genuinely fake fixture, give it a shape a real key cannot have "
        "(shorter, or non-hex) rather than allowlisting it."
    )


def test_detector_catches_a_planted_key(tmp_path):
    """The detector is pointed at a synthetic tree, so a silent no-op is visible."""
    (tmp_path / "scratch.py").write_text(
        'api_key = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"\n',  # obviously fake: the real key must not be re-committed here
        encoding="utf-8",
    )
    assert _key_literal_offenders(tmp_path) == [("scratch.py", 1)]


def test_detector_ignores_a_bare_digest(tmp_path):
    """A sha256 with no credential word on the line is not a finding."""
    (tmp_path / "checksums.json").write_text(
        '{"sha256": "19b413378251d828b0c0347ebcfb50343f3aff8ebd54ee5d0fe439f974dfecb3"}\n',
        encoding="utf-8",
    )
    assert _key_literal_offenders(tmp_path) == []


def test_detector_ignores_an_untracked_key(tmp_path):
    """An ignored file holding a key is out of scope: git will never accept it.

    This is the ``.cache/model.json`` case. The SDK writes a real ``api_key``
    there on every run and .gitignore excludes it, so a tree-wide walk reported
    a leak that no commit could ever contain.
    """
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    (tmp_path / ".gitignore").write_text(".cache/\n", encoding="utf-8")
    (tmp_path / ".cache").mkdir()
    planted = '{"api_key": "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"}\n'
    (tmp_path / ".cache" / "model.json").write_text(planted, encoding="utf-8")
    subprocess.run(["git", "-C", str(tmp_path), "add", ".gitignore"], check=True)

    assert _key_literal_offenders(tmp_path) == []

    # ...and tracking that same content is still a finding, so the scope
    # narrowing above did not simply turn the detector off.
    (tmp_path / "scratch.py").write_text(f"api_key = {planted!r}\n", encoding="utf-8")
    subprocess.run(["git", "-C", str(tmp_path), "add", "scratch.py"], check=True)
    assert _key_literal_offenders(tmp_path) == [("scratch.py", 1)]


def _gitleaks_hook_rev():
    """Return the ``rev`` pinned for the gitleaks repo in .pre-commit-config.yaml."""
    config = yaml.safe_load(PRE_COMMIT_CONFIG.read_text(encoding="utf-8"))
    for repo in config["repos"]:
        if repo.get("repo") == GITLEAKS_REPO:
            assert any(hook["id"] == "gitleaks" for hook in repo["hooks"]), "gitleaks repo is present but its hook is not enabled"
            return repo["rev"]
    pytest.fail(f"no {GITLEAKS_REPO} hook in .pre-commit-config.yaml; secrets would reach history unscanned")


def test_gitleaks_hook_is_configured():
    """pre-commit scans the staged diff, the last point a secret can be kept out of history."""
    assert _gitleaks_hook_rev().startswith("v"), "pin the hook to a tag, not a moving ref"


def test_gitleaks_config_extends_default_rules():
    """.gitleaks.toml must add allowlists on top of the curated rules, not replace them."""
    text = GITLEAKS_CONFIG.read_text(encoding="utf-8")
    assert "useDefault = true" in text, (
        ".gitleaks.toml must keep `useDefault = true`: without it only the allowlists "
        "remain and the scanner matches nothing."
    )


def test_ci_scans_the_whole_tree_at_the_pinned_version():
    """The staged-diff hook is a no-op under ``--all-files``; CI scans the tree itself.

    The CI step downloads a pinned release rather than reusing the hook's binary,
    so the two versions can drift apart silently. Assert they match.
    """
    workflow = yaml.safe_load(PRE_COMMIT_WORKFLOW.read_text(encoding="utf-8"))
    steps = workflow["jobs"]["pre-commit"]["steps"]

    scan_steps = [step for step in steps if "gitleaks" in str(step.get("run", ""))]
    assert scan_steps, "no full-tree gitleaks step in .github/workflows/pre-commit.yaml"

    scan = scan_steps[0]
    assert "gitleaks dir" in scan["run"], "the CI scan must use `gitleaks dir`: a commit range is empty on a first push"
    assert "--config .gitleaks.toml" in scan["run"], "the CI scan must use the repo's allowlists"

    ci_version = scan["env"]["GITLEAKS_VERSION"]
    assert f"v{ci_version}" == _gitleaks_hook_rev(), (
        f"CI pins gitleaks {ci_version} but .pre-commit-config.yaml pins {_gitleaks_hook_rev()}; "
        "a rule fixed in one version but not the other makes the two scans disagree."
    )
