"""Drift guard for the aiXplain SDK v1 sunset notice.

The v1 removal date used to live only in prose, duplicated across several READMEs, and
it silently expired. ``aixplain._compat.V1_REMOVAL_DATE`` is now the single source of
truth; this module fails CI whenever a hand-written doc disagrees with it, whenever the
Arabic docs fall behind the English ones, or whenever a public v1 factory is missing
from ``MIGRATION.md``.
"""

import datetime
import importlib
import inspect
import pathlib
import re

import pytest

from aixplain._compat import (
    MIGRATION_GUIDE_URL,
    SUPPRESS_ENV_VAR,
    V1_REMOVAL_DATE,
    V1_REMOVAL_DATE_HUMAN,
)

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]

#: Hand-written docs that must carry the sunset notice. Anything under
#: ``docs/api-reference/`` is generated by .github/workflows/docs.yaml and excluded.
DOCS_WITH_NOTICE = [
    "README.md",
    "README.ar.md",
    "AGENTS.md",
    "AGENTS.ar.md",
    "docs/README.md",
    "docs/README.ar.md",
    "MIGRATION.md",
]

#: English/Arabic doc pairs. If the English file mentions the removal date, its Arabic
#: counterpart must too — the original notice shipped English-only for a full release.
TRANSLATION_PAIRS = [
    ("README.md", "README.ar.md"),
    ("AGENTS.md", "AGENTS.ar.md"),
    ("docs/README.md", "docs/README.ar.md"),
]

#: English-language docs, which must also spell the date out in prose.
ENGLISH_DOCS = ["README.md", "AGENTS.md", "docs/README.md", "MIGRATION.md"]

#: Dates that were published before the notice was made executable. They must not
#: survive anywhere in the hand-written docs.
OBSOLETE_DATES = ["August 1, 2026", "2026-08-01"]


def read(relative_path):
    """Return the text of a repo-relative doc, failing loudly if it is missing."""
    path = REPO_ROOT / relative_path
    assert path.is_file(), f"expected doc {relative_path} to exist at {path}"
    return path.read_text(encoding="utf-8")


# -- The removal date agrees everywhere ---------------------------------------------


def test_removal_date_constants_agree():
    """The human rendering must describe the same day as the machine-readable date."""
    year, month, day = (int(part) for part in V1_REMOVAL_DATE.split("-"))
    month_name = [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
    ][month - 1]
    assert V1_REMOVAL_DATE_HUMAN == f"{month_name} {day}, {year}"


def test_removal_date_has_not_silently_expired():
    """The tripwire whose absence is the whole reason this module exists.

    The previous sunset date (2026-08-01) came and went with nothing in the code, the
    tests, or CI noticing — v1 was documented as removed while still shipping, warning
    nobody. Every other check here guards against the docs *disagreeing* with
    :data:`V1_REMOVAL_DATE`; none of them notice when the date itself goes stale, so a
    silent expiry could happen a second time.

    This fails the build on the removal date. That is the point: the deadline arriving
    should force a decision — ship the removal, or move the date deliberately — rather
    than pass unremarked. Both branches are one-line edits to
    ``aixplain._compat.V1_REMOVAL_DATE`` plus the docs it drives.
    """
    removal = datetime.date.fromisoformat(V1_REMOVAL_DATE)
    today = datetime.date.today()
    assert today < removal, (
        f"The advertised v1 removal date {V1_REMOVAL_DATE} has passed (today is {today}), "
        f"and v1 is still shipping. Either remove v1, or move "
        f"aixplain._compat.V1_REMOVAL_DATE (and V1_REMOVAL_DATE_HUMAN) to a new date and "
        f"update the docs listed in DOCS_WITH_NOTICE. Do not delete this test — a sunset "
        f"date nobody checks is exactly the defect this suite was written to prevent."
    )


@pytest.mark.parametrize("doc", DOCS_WITH_NOTICE)
def test_doc_carries_the_machine_readable_removal_date(doc):
    """Every hand-written doc anchors on the ISO date, in any language."""
    assert V1_REMOVAL_DATE in read(doc), (
        f"{doc} does not mention the v1 removal date {V1_REMOVAL_DATE}. "
        f"Update it, or update aixplain._compat.V1_REMOVAL_DATE if the date changed."
    )


@pytest.mark.parametrize("doc", ENGLISH_DOCS)
def test_english_doc_spells_the_date_out(doc):
    """English docs additionally carry the prose form, e.g. "February 1, 2027"."""
    assert V1_REMOVAL_DATE_HUMAN in read(doc), f"{doc} does not mention {V1_REMOVAL_DATE_HUMAN!r}"


@pytest.mark.parametrize("doc", DOCS_WITH_NOTICE)
@pytest.mark.parametrize("obsolete", OBSOLETE_DATES)
def test_no_obsolete_removal_date_survives(doc, obsolete):
    """The superseded date must be gone — a stale sunset date teaches users to ignore it."""
    assert obsolete not in read(doc), f"{doc} still advertises the superseded removal date {obsolete!r}"


def shipped_markdown_files():
    """Yield the repo's hand-written Markdown docs.

    Excludes ``docs/api-reference/`` (regenerated by .github/workflows/docs.yaml) and any
    dot-directory — ``.git``, plus agent/tooling scratch space that legitimately quotes
    the superseded date when describing this very deprecation.
    """
    for path in REPO_ROOT.rglob("*.md"):
        relative = path.relative_to(REPO_ROOT)
        if any(part.startswith(".") for part in relative.parts):
            continue
        if "api-reference" in relative.parts:
            continue
        yield relative, path


def test_no_obsolete_removal_date_anywhere_in_hand_written_docs():
    """Catch stale dates in docs not listed in DOCS_WITH_NOTICE."""
    offenders = [
        str(relative)
        for relative, path in shipped_markdown_files()
        if any(obsolete in path.read_text(encoding="utf-8") for obsolete in OBSOLETE_DATES)
    ]
    assert offenders == [], f"these docs still advertise a superseded v1 removal date: {offenders}"


def test_the_obsolete_date_scan_actually_reads_files():
    """Guard the guard: an empty file list would make the scan above vacuous."""
    scanned = [str(relative) for relative, _ in shipped_markdown_files()]
    assert "README.md" in scanned and "MIGRATION.md" in scanned, scanned


# -- The Arabic docs must not fall behind ------------------------------------------


@pytest.mark.parametrize(("english", "arabic"), TRANSLATION_PAIRS)
def test_arabic_doc_carries_the_notice_whenever_the_english_one_does(english, arabic):
    """The parity check: an English-only sunset notice is the bug this guards against."""
    if V1_REMOVAL_DATE not in read(english):
        pytest.skip(f"{english} does not carry the notice, so there is nothing to mirror")
    assert V1_REMOVAL_DATE in read(arabic), (
        f"{english} carries the v1 sunset notice but {arabic} does not. "
        f"Arabic-reading users must get the same notice."
    )


@pytest.mark.parametrize(("_english", "arabic"), TRANSLATION_PAIRS)
def test_arabic_doc_links_the_migration_guide(_english, arabic):
    """A notice with no migration path is a dead end in any language."""
    assert "MIGRATION.md" in read(arabic), f"{arabic} does not link MIGRATION.md"


# -- MIGRATION.md covers the whole public v1 surface -------------------------------


def public_v1_factories():
    """Return the names of every factory class exported from ``aixplain.v1.factories``.

    Introspected rather than hardcoded so that adding a factory without documenting it
    fails this test instead of going silently unmigrated.
    """
    module = importlib.import_module("aixplain.v1.factories")
    return sorted(
        name
        for name, obj in vars(module).items()
        if inspect.isclass(obj) and name.endswith("Factory") and not name.startswith("_")
    )


def test_public_v1_factories_are_discoverable():
    """Guard the guard: if introspection returns nothing, the coverage test is vacuous."""
    factories = public_v1_factories()
    assert len(factories) >= 17, f"expected the full v1 factory surface, found {factories}"


@pytest.mark.parametrize("factory", public_v1_factories())
def test_migration_guide_documents_every_public_v1_factory(factory):
    """Every exported factory needs a v2 mapping or an explicit gap entry."""
    assert factory in read("MIGRATION.md"), (
        f"MIGRATION.md does not mention {factory}. Every public v1 factory needs a v2 "
        f"mapping or an explicit 'no v2 equivalent yet' entry."
    )


def test_migration_guide_documents_script_factory():
    """``ScriptFactory`` is reachable via its module but not exported, so it is easy to miss."""
    assert "ScriptFactory" in read("MIGRATION.md")


def test_migration_guide_documents_the_suppression_switch():
    """Users told to migrate also need to know how to quiet the notice meanwhile."""
    migration = read("MIGRATION.md")
    assert SUPPRESS_ENV_VAR in migration
    assert "AixplainV1DeprecationWarning" in migration


# -- The docs and the warning point at each other ----------------------------------


def test_migration_guide_url_matches_the_repo_layout():
    """The URL baked into the warning must resolve to the file we actually ship."""
    assert MIGRATION_GUIDE_URL.endswith("/MIGRATION.md")
    assert (REPO_ROOT / "MIGRATION.md").is_file()


@pytest.mark.parametrize("doc", ["README.md", "docs/README.md"])
def test_english_readme_links_the_migration_guide(doc):
    """The READMEs are where users start, so the guide must be reachable from them."""
    assert re.search(r"\(\.?/?MIGRATION\.md\)|MIGRATION\.md", read(doc)), f"{doc} does not link MIGRATION.md"
