name: Run Tests

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
  workflow_dispatch:  

jobs:
  test-setup:
    runs-on: ubuntu-latest
    outputs:
      TEAM_API_KEY: ${{ secrets.TEAM_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest

      - name: Set environment variables
        run: |
          echo "TEAM_API_KEY=${{ secrets.TEAM_API_KEY }}" >> $GITHUB_ENV
          echo "BACKEND_URL=https://test-platform-api.aixplain.com/" >> $GITHUB_ENV
          echo "MODELS_RUN_URL=https://test-models.aixplain.com/api/v1/execute" >> $GITHUB_ENV
          echo "PIPELINES_RUN_URL=https://test-platform-api.aixplain.com/assets/pipeline/execution/run" >> $GITHUB_ENV

  test-general-assets:
    needs: test-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run general_assets
        run: python -m pytest tests/functional/general_assets
        continue-on-error: true

  test-file-asset:
    needs: test-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run File Asset
        run: python -m pytest tests/functional/file_asset
        continue-on-error: true

  test-agent:
    needs: test-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Agent
        run: python -m pytest tests/functional/agent
        continue-on-error: true

  test-team-agent:
    needs: test-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Team Agent
        run: python -m pytest tests/functional/team_agent
        continue-on-error: true

  test-data-asset:
    needs: test-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Data
        run: python -m pytest tests/functional/data_asset
        continue-on-error: true

  test-benchmark:
    needs: test-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Benchmark
        run: python -m pytest tests/functional/benchmark
        continue-on-error: true

  test-pipelines:
    needs: test-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Pipelines
        run: python -m pytest tests/functional/pipelines
        continue-on-error: true

  test-api-key:
    needs: test-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Api Key
        run: python -m pytest tests/functional/apikey
        continue-on-error: true

  test-finetuner:
    needs: test-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Finetuner
        run: python -m pytest tests/functional/finetune
        continue-on-error: true
