name: Run Tests

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest
      - name: Set environment variables
        run: |
          echo "TEAM_API_KEY=${{ secrets.TEAM_API_KEY }}" >> $GITHUB_ENV

      - name: Run Tests
        run: python -m pytest tests/functional/general_assets
